version: '3'

services:
  peerjs-server:
    build: 
      context: ./docker/peerjs-server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9000:9000"
    restart: always
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - peerjs-server
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d